Repository wsu-cpts489-fa20/bp-kliks, pull requests merged in 2020-11, with the labels that each got.

#12 added the check upon creation of an account and removed the sign with…
  client/src/components/CreateEditAccountDialog.js
  client/src/components/LoginPage.js
Labels: documentation

#14 Obakari/instructor view
  client/src/AppMode.js
  client/src/components/App.js
  client/src/components/LoginPage.js
  client/src/components/ModeBar.js
  client/src/components/NavBar.js
  client/src/components/SideMenu.js
  client/src/components/SurveyManagement/ActiveQuestions.js
  client/src/components/SurveyManagement/AnswerTypes/FileUpload.js
  client/src/components/SurveyManagement/AnswerTypes/FreeResponse.js
  client/src/components/SurveyManagement/AnswerTypes/MultipleChoice.js
  client/src/components/SurveyManagement/CreateSurvey.js
  client/src/components/SurveyManagement/SearchQuestions.js
  client/src/components/SurveyManagement/SubmittedResponse.js
  client/src/components/SurveyManagement/surveyItem.js
  client/src/components/SurveyManagementPage.js
  client/src/styles/index.css
  package.json
Labels: documentation

#22 Marco/user route
  server/routes/user.js
Labels: Story Points: 3, documentation

#23 Marco/courses route
  server/routes/course.js
Labels: Story Points: 3, documentation

#26 Obakari/crud responses
  server/routes/response.js
  server/schemas/response.js
Labels: Story Points: 3, documentation

#24 Rebecca/student route
  server/routes/course.js
  server/routes/student.js
Labels: Story Points: 3, documentation

#31 Rebecca/manage courses - implemented basic tables for courses & students and allow instructors to upload a csv file of students
  client/src/AppMode.js
  client/src/components/App.js
  client/src/components/CourseManagement/AddStudent.js
  client/src/components/CourseManagement/CoursesPage.js
  client/src/components/CourseManagement/CoursesTable.js
  client/src/components/CourseManagement/StudentsTable.js
  client/src/components/CourseManagement/UploadStudents.js
  client/src/components/CoursesPage.js
  client/src/components/FloatingButton.js
  client/src/styles/index.css
Labels: Story Points: 8, enhancement

#28 Erosa - created the survey routes for POST, PUT, DELETE and READ
  server/routes/survey.js
Labels: Story Points: 3, documentation

#34 marco arceo - Fixed the name of the ErrMsg to errorMsg since it did n…
  client/src/components/LookUpAccountDialog.js
Labels: bug
