Repository wsu-cpts489-fa20/bp-kliks, pull requests merged in 2020-12, with the labels that each got.

#42 Rebecca/testing config
  client/src/components/CourseManagement/CoursesPage.js
  client/src/components/CourseManagement/CoursesTable.js
  client/src/components/CourseManagement/StudentsTable.js
  client/src/components/CourseManagement/UploadStudents.js
  client/src/components/CreateEditAccountDialog.js
  client/src/components/FeedPage.js
  client/src/components/LoginPage.js
  client/src/components/LookUpAccountDialog.js
  client/src/components/ModeBar.js
  client/src/components/NavBar.js
  client/src/components/ResetPasswordDialog.js
  client/src/components/SecurityQuestionDialog.js
  client/src/components/SideMenu.js
  client/src/components/SurveyManagement/ActiveQuestions.js
  client/src/components/SurveyManagement/DeleteResponseModal.js
  client/src/components/SurveyManagement/SubmittedResponse.js
  client/src/components/SurveyManagement/ViewResponseModal.js
  client/src/tests/CoursesTests.js
  client/src/tests/DashboardTests.js
  client/src/tests/LoginTests.js
  client/src/tests/PasswordResetTest.js
  client/src/tests/README.md
  client/src/tests/StudentTests.js
  client/src/tests/SurveyManagementTests.js
  client/src/tests/UserTests.js
  client/src/tests/config.js
Labels: Story Points: 1, enhancement

#45 Rebecca/courses mode
  client/src/AppMode.js
  client/src/components/App.js
  client/src/components/CourseManagement/AddCourse.js
  client/src/components/CourseManagement/CoursesPage.js
  client/src/components/CourseManagement/CoursesTable.js
  client/src/components/CourseManagement/DeleteCourse.js
  client/src/components/CourseManagement/EditCourse.js
  client/src/components/CourseManagement/StudentsTable.js
  client/src/components/SideMenu.js
  client/src/styles/index.css
Labels: enhancement

#43 Obakari/responsefile types
  client/src/components/SurveyManagement/AnswerTypes/FileUpload.js
  server/routes/question.js
  server/schemas/question.js
Labels: Story Points: 1, documentation

#62 -ob-all objects that will be created should have unique ids
  client/src/components/SurveyManagement/CreateQuestion.js
  client/src/components/SurveyManagement/CreateSurvey.js
  server/routes/course.js
  server/routes/question.js
  server/routes/response.js
  server/routes/survey.js
Labels: Story Points: 1, enhancement

#68 Obakari/delete surveys
  client/src/components/App.js
  client/src/components/CourseManagement/CoursesPage.js
  client/src/components/CourseManagement/CoursesTable.js
  client/src/components/SurveyManagement/ConfirmDeleteSurvey.js
  client/src/components/SurveyManagement/CreateQuestion.js
  client/src/components/SurveyManagement/CreateSurvey.js
  client/src/components/SurveyManagement/SearchSurveys.js
  client/src/components/SurveyManagement/SortTypes.js
  client/src/components/SurveyManagementPage.js
  install_build.sh
  server/routes/course.js
  server/routes/student.js
  server/routes/survey.js
Labels: Story Points: 5, enhancement

#63 Rebecca/courses route fix
  client/src/components/App.js
  client/src/components/CourseManagement/CoursesPage.js
  client/src/components/CourseManagement/CoursesTable.js
  server/routes/course.js
  server/routes/student.js
Labels: Story Points: 3, bug

#64 Marco/active question filter
  client/src/components/SurveyManagement/ActiveQuestions.js
  client/src/components/SurveyManagement/SearchQuestions.js
  client/src/styles/index.css
Labels: Story Points: 1, enhancement

#72 Obakari/populate questions
  client/src/components/SurveyManagement/AnswerTypes/FileUpload.js
  client/src/components/SurveyManagement/CreateQuestion.js
  client/src/components/SurveyManagement/SearchQuestions.js
  client/src/components/SurveyManagement/SearchSurveys.js
  client/src/components/SurveyManagementPage.js
Labels: Story Points: 1, enhancement

#73 Rebecca/courses tests
  client/src/components/CourseManagement/CoursesTable.js
  client/src/components/CourseManagement/DeleteCourse.js
  client/src/components/CourseManagement/DeleteStudent.js
  client/src/components/CourseManagement/EditCourse.js
  client/src/components/CourseManagement/StudentsTable.js
  client/src/components/CourseManagement/UploadStudents.js
  client/src/tests/CoursesTests.js
  client/src/tests/uploads/test_upload.csv
Labels: Story Points: 1, Tests

#74 -ob-added the tests for the issue.
  client/src/components/SurveyManagement/SearchQuestions.js
  client/src/tests/SurveyManagementTests.js
Labels: Story Points: 1, Tests
